spring:
  application:
    name: multimedia
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      #key-serializer: org.apache.kafka.common.serialization.StringSerialization
      value-serializer: org.springframework.kafka.support.serializer.JsonSerialization
